### ISSUE TITLE
Feature Suggestion: Check to see if the user has granted permission to access the calendar

### ISSUE THREAD

**Issue by raefa** [EddyVerbruggen/nativescript-calendar#1]
Thanks for the module. Very helpful.

I want to only ask for permission to access the calendar (on iOS) if the user clicks on a button so I only include the module when a button is pressed. If the user has not granted access to their calendar before, including the module will prompt them with a message asking for permission to access their calendar. I want to immediately add an item to their calendar as soon as they have done this ... but I can't because there is no call back. It would be very helpful if the module:
1. Allowed you to query if the user has granted permission.
2. Had a callback after permission has been granted.

**Comment by EddyVerbruggen** [comment]
Hi, I've just completed a total rewrite of the permission structure for iOS and Android. You will no longer be prompted to allow access to the Calendar upon require, but upon actual usage of one of the plugin's features. Nothing to check for you, just invoke the plugin's features as usual.

Will be available from npm in version 1.1.0, and it's immediately available from GitHub.

**Comment by raefa** [comment]
@EddyVerbruggen Just ran into this issue again. It is great that it only prompts you when you need it, but I have run into the situation where someone has denied access the first time, forgotten about that, come back later and pressed a button to add to calendar and nothing happens. In this situation, it would be good to display something rather than nothing happening.

**Comment by raefa** [comment]
I will answer my own question. I see there is a Calendar.requestPermission with an error call back. :) This is working well for me.

```
Calendar.requestPermission().then(
    function() {
      Calendar.createEvent(options).then(
        function(_createdId) {
          Dialogs.alert({
            title: "Added",
            message: "The appointment has been added to your calendar.",
            okButtonText: "OK"
          });
        },
        function(error) {
          if (addToCalendarTries <= 5) {
            addToCalendarTries++;
            setTimeout(function() { addToCalendar(model); }, 1000);
          } else {
            Dialogs.alert({
              title: "Not Added",
              message: "There was an error creating the appointment in your calendar. (" + error + ")",
              okButtonText: "OK"
            });
          }
        }
      );
    },
    function(error) {
      var appendToMessage = Application.ios ? " Go to the Settings App, scroll down to <app name>, and tune on Calendars." : "";
      Dialogs.alert({
        title: "Not Added",
        message: "It appears you did not give access to your calendar." + appendToMessage,
        okButtonText: "OK"
      });
    }
  );
```
