### ISSUE TITLE
findEvents logs an error but returns the correct result (iOS Simulator?)

### ISSUE THREAD

**Issue by grasshoppermouse** [EddyVerbruggen/nativescript-calendar#11]
When I call `Calendar.findEvents(options).then() I always get this error:

```
Error getting calendar item with UUID (null): Error Domain=EKCADErrorDomain Code=1010 "(null)"
```

I do get the calendar events, however.

**Comment by EddyVerbruggen** [comment]
Is that error shown in the console (log), or actually returned in the promise?

**Comment by grasshoppermouse** [comment]
In console.log

**Comment by EddyVerbruggen** [comment]
OK so there's an error in the log but it actually works fine, right?

What device is this and what are the options you pass in?

**Comment by grasshoppermouse** [comment]
Yes, it works fine (the promise returns the correct events). I'm using the Simulator set to iPhone 6,  iOS 10.1 (14B72) on an iMac. Here are the options:

```
        var options = {
            // calendar: {name: this.calendarName},
            startDate: new Date(this.conference.start_date),
            endDate: new Date(this.conference.end_date)
        };
```

**Comment by EddyVerbruggen** [comment]
Thank you!

Testing the Calendar in the iOS Sim is not always perfect, I wonder if that same log ever occurs on a real device. In any case there's not much I see that's currently wrong (in the code).

**Comment by grasshoppermouse** [comment]
OK, this my first go at mobile development. I'll try it on a real device in the next few days and update this issue then.

**Comment by EddyVerbruggen** [comment]
Thank you, and good luck with your project! 👍
