### ISSUE TITLE
Android: Calendar.listCalendars (actually Calendar._findCalendars) results in a crash

### ISSUE THREAD

**Issue by creambyemute** [EddyVerbruggen/nativescript-calendar#12]
Hey there,

So I just updated my apps nativescript-calendar plugin version from 1.0.7 to 1.1.3 (also tried 1.1.1 and 1.1.2) and experience a crash when listing the calendars.

What I do is the following:
My page has a drop down which will/should be filled with available calendars. Therefore I call `Calendar.listCalendars()` in my ngAfterViewInit to fetch the calendars.
If the permission has not been granted yet, the user will be prompted with the permission dialog (so far so good). If the user then grants the permission the `onPermissionGranted` callback from `Calendar.listCalendars()` will be called which will then in turn call `Calendar._findCalendars()`.

In there I receive an exception/stacktrace because `Cannot read property 'getContentResolver()' of undefined` which is the line `application.android.foregroundActivity.getContentResolver()` in _findCalendars()

**Additional info**: If I restart the app after the granting permission crash the listing of the calendars works.

**Comment by EddyVerbruggen** [comment]
Thanks for your excellent bugreport, I'm taking a look..
