### ISSUE TITLE
Possible to specify no reminder?

### ISSUE THREAD

**Issue by grasshoppermouse** [EddyVerbruggen/nativescript-calendar#15]
If I set `options.reminders = null` I then get the default of 60 minutes (at least on iOS). Any way to set the reminder to `None`?

**Comment by erjdriver** [comment]
Seems to be also on Android. Android Calendar can be set to add reminders automatically - I made sure no such defaults were set - but I still get reminders 1 hr before time.

Any way to set no reminders.

Thanks.

**Comment by EddyVerbruggen** [comment]
Can you try to explicitly set `options.reminders.first` to `null` instead of `options.reminders`? Perhaps there's a bug in the merge logic.

**Comment by erjdriver** [comment]
Yes that fixed it.

`        reminders:
        {
          first: null
        }
`

**Comment by EddyVerbruggen** [comment]
Nice, thanks for verifying that suspicion.

**Comment by EddyVerbruggen** [comment]
Fixed in 1.2.1.
