### ISSUE TITLE
Handling the permission dialog

### ISSUE THREAD

**Issue by erjdriver** [EddyVerbruggen/nativescript-calendar#17]
When I run the app for the first time using the calendar api, the plug-in prompts for permissions (Android) and I select 'ALLOW' and then nothing happens.

I have to initiate the action again and then it works.

I'm not calling requestPermission() or hasPermissions().

I call plug-in deleteEvents() and then createEvent().

On a related note, I call deleteEvents() to delete all events within a date range and then call createEvent(). When I review the calendar, some created events are no longer there.

I know deleteEvents() returns a promise - do I need to call createEvent() after a successful return from within the promise?

**Comment by EddyVerbruggen** [comment]
Sounds to me you were using a pre-1.1.0 version of this plugin. Permissions should be automatically handled since.

**Comment by shivgolani** [comment]
@erjdriver facing similar issue. Did you find any solution?
 
When I run the app for the first time using the calendar api, the plug-in prompts for permissions (Android) and I select 'ALLOW' and then nothing happens.

I have to initiate the action again and then it works.

I'm not calling requestPermission() or hasPermissions().

**Comment by EddyVerbruggen** [comment]
@shivgolani Can you post the code triggering this prompt?
