### ISSUE TITLE
[Android] Not setting options.url adds undefined to description

### ISSUE THREAD

**Issue by SjurWarEagle** [EddyVerbruggen/nativescript-calendar#2]
Hi,

I'm using typescript with angular 2 and your plugin in version 1.0.6 :)
When I'm not seting the options.url to null, the created calendar event get's an "undefined" added.

The JSON generated by my program is:
JS: createEvent={"title":"SomeTitle","startDate":"2015-11-03T15:30:00.000Z","endDate":"2015-11-03T17:06:00.000Z","calendar":{"name":"Dummy"},"notes":"SomeText","location":"SomeLocation"}

and this results in "SomeText undefined".
![undefined](https://cloud.githubusercontent.com/assets/7311103/17852310/e84a1132-6866-11e6-9b4b-c7a581eed8e1.jpg)

When setting url to null:
JS: createEvent={"title":"SomeTitle","startDate":"2015-11-03T15:30:00.000Z","endDate":"2015-11-03T17:06:00.000Z","calendar":{"name":"Dummy"},"notes":"SomeText","location":"SomeLocation","url":null}
it works fine.

I would like to not have to set url manually to null.

**Comment by EddyVerbruggen** [comment]
Nice find and thanks for the detailed report!

Fixed in 1.0.7.
