### ISSUE TITLE
Writing events to a shared calendar that's not read-only.

### ISSUE THREAD

**Issue by erjdriver** [EddyVerbruggen/nativescript-calendar#20]
I'm using the plug-in to create events to a calendar that I create implicitly via the plug-in.

There seems to be two problems - the calendar is created locally only - i.e. not sharable and also the events created are read-only.

For the shareable issue, when I log into the same google account on my computer - the created calendar is not visible. Eventually I'd like to pass an url to someone else so that they can view the same events (read-only is fine).

Re the second issue, read-only is ok - the only problem is that if an event from a read-only calendar, google calendar app doesn't open the event in edit mode - resulting in not being able to view the event description/note.

**Comment by EddyVerbruggen** [comment]
I'm guessing this is on Android, can you confirm?

**Comment by EddyVerbruggen** [comment]
Looking at [these lines](https://github.com/EddyVerbruggen/Calendar-PhoneGap-Plugin/blob/6b098d8622b4088758a0e235613258fdffc79278/src/android/nl/xservices/plugins/accessor/AbstractCalendarAccessor.java#L591-L592)

**Comment by erjdriver** [comment]
Yes it's Android.

I looked at the code and I believe the problem is at line 585 - the calendar created is a local one.

To create a shared calendar, looks like you need the gmail account credentials - though I could be wrong.

So, if I go to calendar.google.com first - login under my account name and create a calendar there and then use the same calendar name with the plug-in - the sharing feature works.

Otherwise, it's a local entry. Also using the Google calendar app, you can't tap on the created events to see the details (because it's in r/o mode - i think).

If the calendar from calendar.google.com is used - it's shareable and also can tap on the events in the google app.
