### ISSUE TITLE
How to get recurrence value on findEvents method?

### ISSUE THREAD

**Issue by nrbn** [EddyVerbruggen/nativescript-calendar#26]
I am trying to create calendar and i want to add all events to calendar. I created an event and choosed recurrence weekly. But in my calendar all weekly recurrence  are registered on same day and not weekly. See the screenshots.

Google Calendar get all my events correct. So it is saved correct to calendar! How can i get recurrence value in findEvents method?

![screenshot_1507976799](https://user-images.githubusercontent.com/10879727/31574932-f576c4aa-b0da-11e7-9e83-ff8ad5cefcef.png)
![screenshot_1507976804](https://user-images.githubusercontent.com/10879727/31574933-f6fdea4c-b0da-11e7-98fc-685590fc9c59.png)

**Comment by EddyVerbruggen** [comment]
Should be fixed with 2.0.0. Actually, there was a way to get the correct dates but it was a bit crappy and not x-platform. With 2.0.0 you can check the `recurrence` object that's returned from `findEvents`, and those event dates have been corrected.
