### ISSUE TITLE
Android - how to get the permissions prompt

### ISSUE THREAD

**Issue by erjdriver** [EddyVerbruggen/nativescript-calendar#3]
Am not getting the permissions prompt.

I looked at the code and it should do it automatically on module load - but it's not. I call it explicitly and I get the callback with stat = undefined.

var Calendar = require("nativescript-calendar");

  Calendar.requestPermission().then(  function (stat)
    {
      console.log( "requestPermission=" + stat );

    }, function (e)
    {
      console.log( "requestPermission Error=" + e );
    } );

In the manifest file, i included both READ_CALENDAR and WRITE_CALENDAR - and rebuilt app.

**Comment by EddyVerbruggen** [comment]
And this is on Android 6?

**Comment by erjdriver** [comment]
API 23.

**Comment by EddyVerbruggen** [comment]
Which Marshmallow device are you testing on?

**Comment by erjdriver** [comment]
Just an emulator. I went into the manifest file and I see {N} is setting it to 23.

**Comment by EddyVerbruggen** [comment]
The thing I want to know is.. which Android version is this emulator? 4/5/6/7?

**Comment by erjdriver** [comment]
The emulator is geny and is Android 6.0

**Comment by erjdriver** [comment]
The emulator is actually 5.1.1.

I tried on another emulator (geny) w/o Android 6 - and that's crashing..not sure what the reason for that is.

But I'm trying the one w/ 5.1.1

**Comment by EddyVerbruggen** [comment]
There's only a permission prompt on Android 6+. Older ones don't need it. 

And try a real device as emulators mail not all have mail apps. And on iOS it's buggy as hell so disabled on emulator.

**Comment by erjdriver** [comment]
Thanks.

I was going thru your code and noticed that (on the Android) when requesting permissions, you call ActivityCompat.requestPermissions() - but don't listen to the callback after the user grants or rejects. Can something like that be done in {N}? Or do we call requestPermissions() and then wait some time and call hasPermissions()?

Not too familiar with plugins etc - can I edit your file and will it all be compiled automatically or you have to do it? I want to remove that anonymous function that checks permissions on module load.

Thanks again.
