### ISSUE TITLE
I could not get notes, rrule, begin, end values on ios!

### ISSUE THREAD

**Issue by nrbn** [EddyVerbruggen/nativescript-calendar#31]
Hi,

I finished the Android version and working with IOS. And there is something that does not work on ios. I do not get up note, rrule (begin and end) values. I have tried to look at the plugin code, but find no solution.

Can anyone help me find a note, rrule its start and end data?

That picture is ios calendar app (showing note) and my app (no note).
![simulator screen shot 9 dec 2017 13 17 49](https://user-images.githubusercontent.com/10879727/33795578-77eb286a-dce4-11e7-94b5-5f2e22ac22a1.png)

![simulator screen shot 9 dec 2017 13 16 26](https://user-images.githubusercontent.com/10879727/33795579-7be3280a-dce4-11e7-99bf-c8f400467f09.png)

**Comment by EddyVerbruggen** [comment]
Hmm, indeed, `notes` is not returned on iOS. TypeScript FTW:

![notes](https://user-images.githubusercontent.com/1426370/36665202-3c1e695a-1ae7-11e8-84a4-bbc69a699b98.gif)

**Comment by EddyVerbruggen** [comment]
I've added a new `recurrence` return type for `findEvents` with properties: `frequency`, `interval`, and `endDate`. This is available on both platforms in version 2.0.0. I've removed the the other recurrence stuff in the returned object.
