### ISSUE TITLE
App crash when denying permissions

### ISSUE THREAD

**Issue by gabitoesmiapodo** [EddyVerbruggen/nativescript-calendar#33]
- Platform: Android 6 / 7 / etc.
- Plugin version: 1.2.2
- NS CLI / Core Modules Version: 3.3.0
- Using NS + Angular in this case.

Hi, this plugin seems to be causing apps to crash when denying (any) permissions on Android.

For example:

1. Open an app which includes this plugin and any other plugin (camera plugin, geolocation, etc.).
2. At any moment, request permissions for geolocation (or any other feature).
3. Deny the permission(s).
4. The app will (most probably) crash.

The same if you deny permissions for any plugin (being it the calendar plugin, camera, or whatever).

It's not necessary to try to perform any other actions (for example to try to take a picture), apps seems to crash simply by denying any permission(s). 

It seems that by just having 

`import * as Calendar from 'nativescript-calendar';`

in some component and, for example 

`Calendar.createEvent(options)`

the app will crash.

This comment points to where the problem could be https://github.com/NativeScript/nativescript-geolocation/issues/94#issuecomment-351985038

Specifically this line seems to be causing the problem by trying to handle all permission requests https://github.com/EddyVerbruggen/nativescript-calendar/blob/fbaa48cbd3dbbfe0dfd78f3e78f489cd5d795e83/calendar.android.js#L26

Other than this, the plugin seems to work fine.

**Comment by EddyVerbruggen** [comment]
Oh.. thanks, that's not good - the plugin should only handle Calendar related permission and ignore all others.
