### ISSUE TITLE
Events not being added in iOS 11.2

### ISSUE THREAD

**Issue by jayellis** [EddyVerbruggen/nativescript-calendar#36]
It works great in iOS 10 however iOS 11 does not add to calendar.

I've just added the calendar manually and it now creates the events.

**Comment by EddyVerbruggen** [comment]
This video of the demo app begs to differ:

![calendar](https://user-images.githubusercontent.com/1426370/36641210-2307357a-1a2c-11e8-8c0f-f63c349c56b8.gif)
