### ISSUE TITLE
Unexpected results while adding events without and with calendar name

### ISSUE THREAD

**Issue by rowdyrabouw** [EddyVerbruggen/nativescript-calendar#38]
Using the code below will show an alert that the event is created, but it is not visible in the default calendar (tested with iOS 10 and 11 emulator).

If I add 
```
      name: "MyCalendar",
```
the event is created in the calendar of the iOS emulator, but in the default calendar, not in MyCalendar.

```
AddtoCalendar() {
    console.log(new Date(new Date().getTime() + 60 * 60 * 1000));
    console.log(new Date(new Date().getTime() + 2 * 60 * 60 * 1000));
    this.createEvent({
      // spans an hour
      title: "Get groceries",
      location: "The shop",
      startDate: new Date(new Date().getTime() + 60 * 60 * 1000),
      endDate: new Date(new Date().getTime() + 2 * 60 * 60 * 1000)
    });
  }

  private createEvent(options): void {
    Calendar.createEvent(options).then(
      createdId => {
        alert({
          title: "Event created with ID",
          message: JSON.stringify(createdId),
          okButtonText: "OK, nice!"
        });
      },
      error => console.log("doCreateEvent error: " + error)
    );
  }
```

**Comment by EddyVerbruggen** [comment]
That's the code of the demo app, but you didn't include [the bit that specifies the calendar](https://github.com/EddyVerbruggen/nativescript-calendar/blob/c7bb2d48a02b765cd7096b028dd27216a4c5f438/demo/app/main-view-model.ts#L92-L95) so this looks right to me.

See this video of the demo app where the Calendar doesn't yet exist, and the event is created in the new calendar specified in the `createEvent` function:

![calendar](https://user-images.githubusercontent.com/1426370/36641205-0690be20-1a2c-11e8-8542-fa0e96db0793.gif)
