### ISSUE TITLE
NPE on Android in _requestPermission executed by timeout

### ISSUE THREAD

**Issue by creambyemute** [EddyVerbruggen/nativescript-calendar#5]
Hey,

I just tried to integrate your plugin:

1. Added plugin
2. Added require in my component
3. Added uses-permission to the manifest
4. Started/Built app for Android

I didn't do anything else than requiring it yet and I am facing an NPE on startup of the component:

android.support.v4.app.ActivityCompat.requestPermissions in Calendar._requestPermission throws an NPE. 

"Attempt to invoke virtual method 'void android.app.activity.requestPermissions(params...)' on a null object reference"

There is a function/timer in the calendar.android.js which execute _requestPermission after a second and that's what fails.
(function () {
    setTimeout(function() {
        if (!Calendar._hasPermission()) {
            Calendar._requestPermission();
        }
    }, 1000);
})();

If I remove this timer everything works fine and I could add a tap action to a button which then requests permission.

Do we even need this timer? Isn't it better to request permission when it will actually be needed/used?

Cheers,

**Comment by creambyemute** [comment]
Additional info:
We found out that it doesn't happen on a Nexus 5 with Android 6 but on the Nexus 5X with Android 7. So it's most likely something to do with Android 7

**Comment by EddyVerbruggen** [comment]
Luckily I have an Android 7 device now so I'll give it a shot soon.

**Comment by EddyVerbruggen** [comment]
Hi @creambyemute I think it's because the Android application object is `null` at the moment this fires. I really need to rewrite that permission logic.

In the meanwhile, could it be you're requiring this plugin before the app started? Perhaps you can try proving this hypothesis by requiring the plugin at the moment you need it.

**Comment by EddyVerbruggen** [comment]
Hi, I've just completed a total rewrite of the permission structure for iOS and Android. You will no longer be prompted to allow access to the Calendar upon require, but upon actual usage of one of the plugin's features. Nothing to check for you, just invoke the plugin's features as usual.

Will be available from npm in version 1.1.0 but I'd like you to test it first by installing the plugin from GitHub. Would be great if you have the time to give it a spin and provide some feedback!
