### ISSUE TITLE
Read and Write Permission Error in Android 8

### ISSUE THREAD

**Issue by fernandojne20** [EddyVerbruggen/nativescript-calendar#53]
Hi Guys, I need a big help here please, i'm facing an error that only seems to happen in Android 8, 
when the application request for permission and i granted, the app crashes, then I open again the application, and try to create an Event with the createEvent method, and get the error i posted below.

i have in the manifest file this permissions too.

`<uses-permission android:name="android.permission.READ_CALENDAR"/>
<uses-permission android:name="android.permission.WRITE_CALENDAR"/>`

I any other Android version i have tested work perfect.

I will thankful for any help you can provide me!

`JS: Error in Calendar.createEvent: Error: java.lang.SecurityException: Permission Denial: reading com.android.providers.calendar.CalendarProvider2 uri content://com.android.calendar/calendars from pid=2278, uid=10068 requires android.permission.READ_CALENDAR, or grantUriPermission()
JS:     android.os.Parcel.readException(Parcel.java:1942)
JS:     android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
JS:     android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
JS:     android.content.ContentProviderProxy.query(ContentProviderNative.java:418)
JS:     android.content.ContentResolver.query(ContentResolver.java:754)
JS:     android.content.ContentResolver.query(ContentResolver.java:704)
JS:     android.content.ContentResolver.query(ContentResolver.java:662)
JS:     com.tns.Runtime.callJSMethodNative(Native Method)
JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1116)
JS:     com.tns.Runtime.callJSMethodImpl(Runtime.java:996)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:983)
JS:     com.tns.Run...
JS: Error creating the event Error: java.lang.SecurityException: Permission Denial: reading com.android.providers.calendar.CalendarProvider2 uri content://com.android.calendar/calendars from pid=2278, uid=10068 requires android.permission.READ_CALENDAR, or grantUriPermission()
JS:     android.os.Parcel.readException(Parcel.java:1942)
JS:     android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
JS:     android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
JS:     android.content.ContentProviderProxy.query(ContentProviderNative.java:418)
JS:     android.content.ContentResolver.query(ContentResolver.java:754)
JS:     android.content.ContentResolver.query(ContentResolver.java:704)
JS:     android.content.ContentResolver.query(ContentResolver.java:662)
JS:     com.tns.Runtime.callJSMethodNative(Native Method)
JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1116)
JS:     com.tns.Runtime.callJSMethodImpl(Runtime.java:996)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:983)
JS:     com.tns.Runtime.c...`

**Comment by darkmantle** [comment]
I'm getting the same error.

**Comment by EddyVerbruggen** [comment]
I tried this again with the demo app on an Android 8 simulator and it all worked perfectly fine. However, it seems like your code/device requires `READ` permission whereas the `createEvent` function only requests `WRITE` permission. I guess I can change the plugin to request `READ` permission as well.
