### ISSUE TITLE
Returning E-Mail for Attendees

### ISSUE THREAD

**Issue by sebastian-julius** [EddyVerbruggen/nativescript-calendar#54]
Hi @EddyVerbruggen,

I'd like to read the e-mail address of an attendee. After playing around a little, I've found that you could get it easily via `ekParticipant.URL.resourceSpecifier` in line https://github.com/EddyVerbruggen/nativescript-calendar/blob/master/src/calendar.ios.ts#L167 . The code could look like this:

```javascript
attendees.push({
    name: ekParticipant.name,
    email: ekParticipant.URL.resourceSpecifier,
    url: ekParticipant.URL,
    status: attendeeStatuses[ekParticipant.participantStatus],
    role: attendeeRoles[ekParticipant.participantRole],
    type: attendeeTypes[ekParticipant.participantType]
});
``` 

As you haven't published any contribution guidelines I wasn't sure whether you'd like to receive PRs or not. Let me know if so, otherwise it'd be awesome if you could add the e-mail field. It'd be great if it could be optional in the TypeScript type https://github.com/EddyVerbruggen/nativescript-calendar/blob/master/src/index.d.ts#L183.

Thanks a bunch

**Comment by EddyVerbruggen** [comment]
Hi!

Good idea. Of course I ❤️PR's. There are a few merged ones [here](https://github.com/EddyVerbruggen/nativescript-calendar/pulls?q=is%3Apr+is%3Aclosed).

Are you able to add that for Android as well?

Thanks,
Eddy

**Comment by slejnej** [comment]
Hi.
Created a pull request for Android support.
Thanks

**Comment by slejnej** [comment]
@EddyVerbruggen 
I've fixed the merge. Building now OK. Thanks

**Comment by slejnej** [comment]
@sebastian-julius did you create a pull request for this? I did the android part but would be great to have same thing in iOS.

**Comment by EddyVerbruggen** [comment]
Wonderful!
