### ISSUE TITLE
Cannot get list of calendars awailable.

### ISSUE THREAD

**Issue by NeevorPL** [EddyVerbruggen/nativescript-calendar#57]
Hi,

I'm trying to use this plugin in my app.
I enabled Calendar API in Google Console, also I have included READ_CALENDAR permission into manifest.

Code:
```
  import * as Calendar from 'nativescript-calendar';

      Calendar.hasPermission().then((g)=> console.log("Permission granted?", g ? "YES" : "NO"));
      Calendar.requestPermission().then((r)=> console.info(r));
      Calendar.listCalendars().then(
        (c)=> {
          console.dir(c);
          this.calendars= c;
          this.isLoading= false;
        },
        (e)=> {
          console.error(e);
          this.isLoading= false;
        }
      );
````
And result in console:

> JS: 'Error in Calendar.requestPermission: Error: java.lang.NullPointerException: Attempt to invoke virtual method \'void android.app.Activity.requestPermissions(java.lang.String[], int)\' on a null object reference'
> JS: 'Error in Calendar.listCalendars: Error: java.lang.NullPointerException: Attempt to invoke virtual method \'void android.app.Activity.requestPermissions(java.lang.String[], int)\' on a null object reference'
> JS: 'Permission granted?' 'NO'
> JS: Error: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.requestPermissions(java.lang.String[], int)' on a null object reference

> 

Any ideas what is wrong?

**Comment by EddyVerbruggen** [comment]
Please try the demo app and (if it works) copy its code. It doesn't seem like your awaiting the result of the `requestPermission` call for instance.
